suttacentral/suttacentral

server/server/data_loader/biblio.py
Just changing the filename from biblio_volpage.json to biblio.json. The file does not contain volpage info.
=> biblio change name

client/elements/sc-donate-now-page.html
Not sure what went wrong here. I had done this but for some reason the tooltip appeared back in the wrong place once I pulled development. So doing it again now.
=> [SUCE-374] error in ticket merge

server/server/common/arangodb.py, server/server/common/models.py, server/server/data_loader/arangoload.py, server/server/data_loader/biblio.py, server/server/data_loader/change_tracker.py, server/server/data_loader/currencies.py, server/server/data_loader/dictionaries.py, server/server/data_loader/dictionary_full.py, server/server/data_loader/divisions.py, server/server/data_loader/homepage.py, server/server/data_loader/images_files.py, server/server/data_loader/paragraphs.py, server/server/data_loader/po.py, server/server/data_loader/textdata.py
I uncovered some serious issues with import_bulk causing errors to be silently ignored.
I made a bug report on the python-arango repo and it's getting some attention.
My interim solution is to patch in a new method that is safer and reports all errors - at the moment it doesn't raise an exception because it would cause the load-data to fail.
Bewarned: it logs A LOT of errors, that are currently being silently ignored with data not being loaded into the database.
=> Import bulk refactor

client/elements/sc-page-search.html, server/server/search/view.py
Now just returns an object of {'total': 42, hits: [...]}
And the hits do not contain underscore properties.
=> Removed all traces of Elasticsearch-cruft from API search results

client/elements/menus/sc-language-menu.html, client/elements/suttaplex/sc-parallel-item.html
An accidental en-dash had crept into the language menu so now removed and replaced by -- again.
=> language dropdown ranges fixed

server/server/data_loader/arangoload.py
not based on the uid (relevant to uids like ds1.1.1, ds 2.1.1
=> num is used for sorting so it should be the enumeration order when loading

client/elements/text/sc-segmented-text.html, client/styles/sc-text-paragraph-num-styles.html
This does not fix the issue with keeping an indented space in front of the paragraphs when you turn infomode off.
The change on sc-segmented-text is only because I got an error in the consule if there is no segment. You might want to change that.
=> [SUCE-558] labels not showing when infomode is off

client/elements/sc-donate-now-page.html, client/elements/sc-page-static.html
The dom-if on the donate-now page created the problem loading the static pages so this page has to reset manually. This is done now but it creates the problem that when you return to the page, it clears the values but some fields turn red. 
Not critical for launch. More important that the pages load at the top.
=> [SUCE-572] static pages loading at top

docker-compose.yml, nginx/Dockerfile-nginx, nginx/conf.d/pootle.nginx.conf, nginx/conf.d/sc.nginx.conf, nginx/create-certs.sh
Tangentially, changed so they'll listen to the production server names.
=> Setup Nginx so it can communicate using SSL, this is for Cloudflare so self-signed is okay.

client/elements/sc-page-dictionary.html, client/elements/sc-page-search.html, client/elements/sc-page-selector.html, client/elements/sc-page-static.html, client/elements/suttaplex/sc-suttaplex-list.html, client/elements/text/sc-text-page-selector.html, client/index.html, client/localization/elements/sc-page-selector/en.json, client/localization/elements/sc-page-selector/pl.json
I have not touched the Google ones and the Twitter ones are just abbreviated versions of the main description for now but I want to see how this actually works in practice with Twitter and Facebook before finetuning.
For the Google itemprop I will need to revamp the webcomponent as it does not take that into account.
=> [SUCE-627] adding social media data twitter fb

client/elements/sc-page-dictionary.html, client/elements/sc-page-search.html, client/elements/sc-page-selector.html, client/elements/sc-page-static.html, client/elements/suttaplex/sc-suttaplex-list.html, client/elements/text/sc-text-page-selector.html, client/index.html
This fires an event that changes the meta data in index.html. It works well in Console but when I do "view-page-source' it changes it back to default settings so not sure how twitter/fb will react to this but we can try. If this fails, I have no idea.
Actually, if this works we don't need the Sherby-metadata element so I will take it out but lets test first.
=> [SUCE-627] meta data in index

nginx/conf.d/prod.nginx.conf
Headers in Nginx ain't easy because only the headers in the lowest block apply. The prefetch header, when applied, caused the other headers to not be applied. Also the prefetch header confuses Safari 10 and the site not work.
=> Fixed typo in regex and rearranged the headers. 

nginx/conf.d/prod.nginx.conf
being that Content Security Policy is now set on the initial response,
instead of every response EXCEPT the first response which I'm pretty
sure was exactly the wrong behavior.
=> Largely reverted to earlier version, and then fixed it, the primary fix

client/elements/sc-page-search.html
When starting a search, you get to see "0 results" before data is loaded. This has now been fixed
=> fixing 0 search at startup

server/server/search/texts.py
This error seems to happen when the arango cursor times out, once
upon a time the texts were actually stored in arangoDB so keeping
the cursor open made sense to reduce memory use.
Now only the paths are stored in arango, so there's no reason to not
fetch all the results immediately and close the cursor.
=> Hopefully fix issue with Runtime error

client/elements/suttaplex/card/sc-suttaplex.js
I just noticed this small error why the japanese and other 3-letter language code texts were not showing. Not sure how the procudure is right now.
=> SUCE-1370 3-letter languages not showing

client/elements/addons/localization-mixin.js, client/elements/menus/navigation-menu/sc-navigation-menu-css.js, client/elements/menus/navigation-menu/sc-navigation-menu.js, client/elements/menus/sc-language-base-menu-css.js, client/elements/menus/sc-language-base-menu.js, client/elements/sc-static-page-selector.js, client/elements/static/numbering-page.js, client/elements/text/sc-segmented-text.js, client/localization/elements/sc-static-page-selector/zh.json, client/localization/elements/static_numbering-page/zh.json
I don't know that when a pull request is not completed, the newly submitted code will be added to the pull requests…… so this pull requests will have the following updates:
1. Apply pseudo-icons for languages in navagation menu and language dropdown #1368 #1373 #1375
2. fixed "font-synthesis is not working in FF for Chinese l10n" #1262
3. fixed "Missing Pali text in segmented translations". #1236 
4. fixed "Numbering page cannot be displayed correctly for Chinese l10n, and the" 遍号 "should be the" 编号 ". #1409 
Next time, I will submit only one update per pull requests.
=>  Apply pseudo-icons for languages in navagation menu and language dropdown menu

client/utils/suttaplex.js
"Column letter more be restored to parallel root IDs for Chinese texts."
=> fix: Taisho parallels table has missing column letters #1477

client/elements/text/sc-segmented-text.js
Some Pali text does not have a proper structure to generate TOC, so there will be errors when generating TOC.
Solution: filter the generated array to eliminate unexpected values.
=> fix:  Some Pali text cannot be displayed

docker-compose.yml, server/server/common/arangodb.py
See https://github.com/suttacentral/suttacentral/issues/1548
After this 
- With language set to, eg, Afrikaans, menu should show green circle on "Sutta".
- On staging.suttacentral.net/languages, languages other than Pali and English should show up.
If at any point this no longer happens, relevant queries should be modified so that they do not use the ArangoSearch View called `v_text`.
=> Bump ArangoDB 3.5.0 => 3.5.2; Disable hack for silent view corruption bug

client/elements/text/sc-lit-text-page.js, client/elements/text/sc-simple-text.js
1. Rewrite sc-simple-text.js component with litElement.
2. Revise objects in sc-simple-text.js #1499
3. Fix: Pali lookup and Chinese lookup in firefox are invalid in the simple text page.
=> Rewrite sc-simple-text.js component with litElement.

client/elements/static/home-page.js
This makes a few subtle adjustments to styling. Fluid sizing is used for headings; transparent overlay used for figcaption, image fallbacks, a few things like that.
I also used LitElement's `css` tag function for styles, according to the LitElement recommendations:
https://lit-element.polymer-project.org/guide/styles
I just wanted to see if it would work, and hey it did!
=> responsiveness, image sources, etc.

client/elements/styles/sc-layout-bilara-styles.js, client/elements/text/sc-bilara-segmented-text.js, client/elements/text/sc-text-page-selector.js
1. Use sc-bilara-segmented-text.js instead of sc-segmented-text.js.
2. Root text and translated text were all shown by sc-bilara-segmented-text.js.
=> Use bilara-segmented-text instead of old text page

client/elements/sc-page-search.js
This just removes the line 
```
flex-basis: 0.000000001px;
```
in sc-page-search.js. This is bad CSS and was causing problems.
=> remove flex-basis from search results

client/elements/navigation/sc-linden-leaves.js, client/elements/navigation/sc-navigation.js, client/elements/sc-page-selector.js
1. let the site title is only displayed on the home page.
2. limit the ripple boundaries of the breadcrumbs.
3. sc-navigation.js code clean up(Delete redundant `true: false`)
=> Let the site title is only displayed on the home page.

client/elements/static/offline-page.js
Open more PWA enabled browsers to use SC offline function.
At present, PWA is supported by the specific versions of Firefox, edge, IOS Safari and opera browsers.
=> Open more PWA enabled browsers to use SC offline function.

client/elements/navigation/sc-linden-leaves.js
This fixes some small style regressions introduced when using the mwc-icons.
- Stop items from changing position on hover (this is a crude way to do it, I am sure there are better  ways!)
- Ensure correct padding for ripple effect.
- Use `var(--sc-disabled-text-color)` for icons. This is the standard color for icons, not secondary-text-color. It should really be renamed `sc-icon-color` but oh well, nothing is perfect!
=> small style tweaks for breadcrumbs

client/elements/navigation/sc-linden-leaves.js
This just keeps it a bit cleaner by using the `nav li:last-child` selector instead of adding a special class to the last child.
Also, I formatted it with CSS comb.
=> use last-child selector instead of class

client/elements/sc-page-selector.js
The static toolbar appears only on static pages and some style modifications.
=> The static toolbar appears only on static pages.

client/elements/navigation/sc-linden-leaves.js, client/elements/navigation/sc-navigation-styles.js, client/elements/sc-page-selector.js, client/elements/static/home-page.js, client/elements/styles/sc-layout-bilara-styles.js, client/elements/styles/sc-layout-simple-styles.js, client/elements/styles/sc-page-selector-styles.js, client/elements/styles/sc-static-page-selector-styles.js, client/elements/styles/sc-typography-common-styles.js, client/elements/suttaplex/sc-suttaplex-list.css.js, client/elements/text/sc-stepper.js, client/elements/text/sc-text-page-selector.js, client/index.html
This fix adjusts the handling of the top and bottom margins in the various contexts:
- static pages
- nav pages
- suttaplex list
- text pages
- search results
I'm still not happy with the way the foot is placed in the text pages, as it relies on the adding up the height of all other elements, if any of them change it will break. We should use a flexbox method like here, but I can't get it to work.
https://developer.mozilla.org/en-US/docs/Web/CSS/Layout_cookbook/Sticky_footers
=> Make top and bottom margins of content more consistent

client/elements/menus/sc-action-items.js, client/elements/navigation/sc-linden-leaves.js, client/elements/styles/sc-site-layout-styles.js
This makes some small changes to the styles for the header.
- apply background color to whole toolbar to avoid possible gaps in background
- likewise, let font-family be applied globally i.e. `:root {    font-family: var(--sc-sans-font);}`, only change it if using a different font.
- remove unused CSS
- make sure flex styles are applied properly
Also, I have changed to use the "visibility" icon for text settings, with the label "views".
=> Sujato header

client/elements/addons/sc-bottom-sheet.js, client/elements/addons/sc-nav-contents.js, client/elements/addons/sc-toasts.js, client/elements/navigation/sc-linden-leaves.js, client/elements/sc-page-dictionary.js, client/elements/sc-page-search.js, client/elements/sc-page-selector.js, client/elements/static/home-page.js, client/elements/styles/sc-colors-dark.json, client/elements/styles/sc-dict-styles.js, client/elements/styles/sc-site-layout-styles.js, client/elements/styles/sc-typography-common-styles.js, client/elements/styles/sc-utility-styles.js, client/elements/text/sc-stepper.js, client/elements/text/sc-text-page-selector.js, client/index.html
This set of changes addresses a variety of issues with styling, principally dealing with the container behavior, ensuring that pages did not trigger overflows and were flush with the horizontal edges.
A few details.
- For elements such as the stepper and the lookup tool, which appear at the bottom of the page and must be flush with the sides, use `margin: 0 calc(-1 * var(--sc-container-margin))`.
- I have removed the drawer from the dictionary searches, and thus the `drawer` and the `sc-scrollbar` may now be removed entirely from the app.
- I have modernized the CSS, fixed some errors, and linted with CSS comb.
- I apply an explicit height and background color to the breadcrumbs on both `:host` and `nav`. This is so that this element renders the background right away, making the page …
=> Sujato container

client/elements/addons/sc-bottom-sheet.js, client/elements/navigation/sc-linden-leaves.js, client/elements/sc-page-selector.js, client/elements/sc-site-layout.js, client/elements/styles/sc-site-layout-styles.js, client/elements/text/sc-stepper.js, client/elements/text/sc-text-page-selector.js, client/index.html
Some subtle adjustments to sizing of headers, make CSS more consistent.
- Ensure height is explicitly set
- Adjust height of toolbar components to ensure pleasing proportions
- Use consistent flex approach in both breadcrumbs and tab bar.
- Set universal `min-height: 101vh` to avoid resetting page width when scrollbar disappears and reappears.
- Ensure there is as little movement on the page as possible when coming to and from Home page.
=> header height and other tweaks to make page transitions smoother

client/elements/addons/localization-mixin.js, client/elements/addons/sc-bottom-sheet.js, client/elements/menus/sc-action-items.js, client/elements/navigation/sc-navigation-styles.js, client/elements/sc-page-selector.js, client/elements/sc-site-layout.js, client/elements/static/home-page.js, client/elements/styles/sc-site-layout-styles.js, client/elements/styles/sc-typography-common-styles.js, client/elements/suttaplex/card/sc-sutta-parallels.js, client/elements/suttaplex/card/sc-suttaplex-css.js, client/elements/suttaplex/card/sc-suttaplex.js, client/elements/suttaplex/sc-suttaplex-list.css.js, client/elements/text/sc-stepper.js
- Style the parallels on text page top sheet, use `position: absolute`.
- Use `<article>` instead of `<paper-card>` for suttaplex. It turns out we are not actually using any features of the paper card, so we can just use `<article>` and it works fine., And we can remove some dependencies.
- I have adjusted the way the side margins are handled so as to make more efficient use of space on mobiles.
- I tried to introduce a responsive design for the toolbar action items, but I could not do it in pure CSS so I reverted it. See #1792 
There are a few bugs on my local machine. I do not know if these are from changes I am making in this commit, or because there was a bug when upgrading my local system to latest database. Anyway I mention them here:
- Suttaplexes don't display blurbs or legacy …
=> Sujato best

client/elements/addons/sc-top-sheet-views.js, client/elements/menus/sc-language-base-menu-css.js, client/elements/menus/sc-more-menu.js
- use native select
- remove mwc-select
- fix bug with more-menu appearing behind top-sheet. This has removed the z-index from top sheet. It seems okay, but best watch for any unintended side-effects.
=> Sujato topsheet select

client/elements/menus/sc-search-filter-menu.js, client/elements/navigation/sc-navigation-styles.js, client/elements/navigation/sc-navigation.js, client/elements/static-templates/home-page.js, client/localization/elements/sc-language-menu/pt.json, client/localization/elements/sc-language-menu/zh.json, server/server/data_loader/arangoload.py, server/server/data_loader/sc_html.py, server/server/data_loader/textdata.py
This makes a few minor changes that eliminate false flags on `make load-data`
- orphaned texts are `info` so don't show by default
- sc-language-menu I think is a deprecated element, I remove it from localization
- we don't use hgroup, check for header instead
I also made a bunch of changes to sc-data that fix various small errors.
Only remaining error is the zz pages: `Text uids do not match menu uids`. These are not in the menu, they are various demo pages.
Anything else is an actual error!
=> Sujato data clean

client/elements/addons/sc-error-icon.js, client/elements/sc-page-selector.js, client/elements/text/sc-text-page-selector.js, client/localization/elements/sc-error-icon/en.json, client/localization/elements/sc-error-icon/zh.json
The iso code list of routing modules does not contain 'jpn', This causes the URL to not be parsed correctly.
=> Fixed:failure to access Japanese sutta that can't be routed.

client/elements/addons/sc-top-sheet-publication-bilara.js, client/package.json
- adjusts publications.json
- Change prettier settings to `"htmlWhitespaceSensitivity": "css"` (which is modern default). Previous setting created extra space when a tag preceded punctuation, eg. `</span> .`
=> Sujato 200

client/elements/navigation/sc-navigation-common.js, client/elements/navigation/sc-navigation.js, client/elements/navigation/sc-tipitaka.js, client/elements/sc-page-selector.js, client/elements/suttaplex/sc-suttaplex-list.js, client/elements/text/sc-text-page-selector.js, server/server/api/views/views.py, server/server/common/queries.py
Currently, the prev/next name is always obtained from the names collection, such as an4.58, with only pli and German versions, no English version, and the pali name is displayed by default if there is no version of the language.
=> Fixed Prev/next localization and breadcrumbs are still buggy #2046

client/elements/menus/sc-more-menu.js
> There's a small bug affecting this.
> 
> The mwc-check-list-item has an odd UI where there are two clickable fields: the item as a whole, and the actual checkbox. (I think it should be just the checkbox, but this is what the mwc official demo does.) So on the demo, if you click anywhere on the item, it turns the checkbox on or off:
> 
> https://material-components.github.io/material-components-web-components/demos/list/
> 
> On our implementation, however, the *function* works when clicking anywhere on the item, but the check mark does not appear unless you click the checkbox itself. That means you can end up in a state where the dark theme is applied, yet it is not checked:
> 
> ![Screenshot from 2021-03-13 10-46-20](https://user-images.githubusercontent.com/6112010/111010080-8fe99280-8 …
=> Fix a bug of more-menu.

README.md
Fix typo (it's -> its) in the README.
=> Fix typo (it's -> its)

server/server/common/queries.py, server/server/search/texts.py
The code for this PR generates indexes of bilara text.
run `make index-elasticsearch` to rebuild the index.
=> Fixed: Pali texts (and other root texts?) are not showing in search results #2094

.gitignore, client/elements/addons/sc-top-sheet-publication-bilara.js, client/elements/addons/sc-top-sheet-views.js, client/elements/text/sc-bilara-segmented-text.js, server/server/api/views/__init__.py, server/server/api/views/views.py, server/server/app.py, server/server/common/queries.py, server/server/data_loader/arangoload.py, server/server/migrations/migrations/add_available_voices_036.py, server/server/migrations/migrations/add_root_edition_037.py
1. No references are loaded by default.
2. References are loaded on user request via the "Reference" options in the top sheet.
3. Users may select as many sets of references as they wish.
4. User selections are persistent until the user changes it.
5. Load the `root_edition.json` to ArangoDB
6. Add API `API/root_edition`
7. Load the `available_voices` to ArangoDB
8. Add API `API/available_voices`
=> Add reference data to texts on user request.

server/server/common/queries.py, server/server/data_loader/arangoload.py, server/server/data_loader/sc_bilara_data.py, server/server/migrations/migrations/add_bilara_author_edition_039.py
The impact of this update is as follows:
1. Author info of the Suttaplex.
2. Author info of the Parallels.
3. Author info of the Sutta (segmented text).
The modification must ensure that the author information in the above list is consistent with the previous information.
=> Use Bilara author metadata for segmented texts.

client/webpack.common.js
At present, cookies are not used in search results. One possibility is that service-worker caches the search results. I have modified the relevant configuration to see if the problem is solved.
=> Fix: Search returns stale results.

client/elements/text/sc-text-bilara.js
> @ihongda , a feedback concerning the Pali lookup tool: Sometimes it happens that I click on a Pali word and the lookup doesn't open, usually the first time I use the website after booting my computer. I have to reload the page, then the lookup works. (I usually use bilingual view, English/Pali.)
This is feedback from @sabbamitta
This PR fixes the problem and does some code optimization.
=> Fix: Pali lookup fails in some cases.

client/elements/suttaplex/card/sc-parallel-item.js, client/elements/suttaplex/card/sc-suttaplex-css.js, client/elements/suttaplex/card/sc-suttaplex.js, client/utils/suttaplex.js, server/server/common/queries.py, server/server/data_loader/arangoload.py
need to execute `make delete-database` `make load-data`
fixed:
1.The new data is used for the main suttaplex nerdy row, but the old data is still used for the parallels.
2.The vol/page references are not appearing on staging for the Vinaya.
3.The title attribute always be the simple "Volume and page".
=> Tuning: Populate volpage and alt_volpage in text_extra_info.json from bilara-data/reference #2152

client/elements/text/sc-text-bilara.js
When the Pali script selects non-latin and then opens the Chinese segmented text (e.g.  http://localhost/sa1/lzh/sct), 
there will be an error that the text is not loaded.
=> Fix a segmented text page error.

client/elements/menus/sc-action-items-universal.js
This fixes this a11y bug:
https://foo-software-lighthouse-reports.s3.amazonaws.com/report-1629685328338.html#accessibility
=> add missing aria-label for close search

client/elements/addons/sc-localization-mixin.js, client/elements/addons/sc-top-sheet-views.js, server/requirements.txt
Related issues: #2017 #2317
In development mode, the localization file under `client/localization/elements` is used by default, but here is only the English version. If you want to view other localization content in development mode, you need to modify the `__loadLanguage` method of `sc-localization-mixin.js` line `100`: 
`if (!USE_PRODUCTION_LOCALIZATION) {`  to `if (USE_PRODUCTION_LOCALIZATION) {`
In production mode, Blake has copied the localization files to the relevant directory by modifying the configuration file.
=> Modify the code to fit the new localization directory (development mode)

client/elements/styles/sc-layout-bilara-styles.js, client/elements/styles/sc-typography-bilara-styles.js, client/elements/styles/sc-typography-common-styles.js, client/elements/text/sc-text-bilara.js
If want to test, need to manually copy the comment file to the `sc-flask` container.
e.g. `docker cp /download/sc_bilara_data/comment sc-flask:/opt/sc/sc-flask/sc-data/sc_bilara_data`
and then execute `make load-data-no-pull`
=> Implement comments for segmented texts.

client/webpack.common.js, client/webpack.prod.js
`otf` files are currently excluded.
*.LICENSE.txt will be automatically cleared after webpack builds the bundle.
However, the localization file seems to be unable to determine which language should only be loaded.
=> Make the service worker not load pointless files.

client/elements/addons/sc-functions-miscellaneous.js, client/elements/addons/sc-static-page.js, client/elements/suttaplex/sc-suttaplex-list.js, client/elements/text/sc-text-bilara.js, client/elements/text/sc-text-legacy.js
Affected pages:
- Static pages (parameter: lang)
- Suttaplex page (parameter: view)
- Segmented text page (parameters: notes/layout/script/highlight/reference)
- Legacy text page (parameters: highlight/reference)
The effect of the replacement should be the same as before.
Related issue : https://github.com/suttacentral/suttacentral/issues/2413
=> Use `UrlSearchParams` to instead of regex.

client/elements/sc-page-search.js
`"search:hint" just says search:hint`
This is caused by the missing `search:hint` key in the relevant localization file.
e.g.
https://github.com/suttacentral/sc-data/blob/master/sc_bilara_data/root/en/site/interface_root-en-site.json
https://github.com/suttacentral/sc-data/blob/master/sc_bilara_data/translation/de/site/interface_translation-de-site.json
=> Fix: "search:search" just says search:search in breadcrumbs.

client/elements/sc-page-selector.js
There was a related PR before, https://github.com/suttacentral/suttacentral/pull/2305 for the text page URL, 
the current PR is for the dictionary and search page URL.
=> URLs must be case insensitive.

client/elements/sc-map.js, client/elements/sc-page-dictionary.js, client/elements/sc-page-search.js, client/elements/styles/sc-dict-styles.js
This is a preliminary change for map migration (suttacentral/suttacentral#939), **lifting the map implementation from the data repo to the client code**. It consists of two PRs which should happen in order:
1. suttacentral/suttacentral#2474 (this PR)
2. suttacentral/sc-data#143
This should bring no changes in functionality or visuals, except:
- In both places where a map can be shown (search page and dictionary page) the margins are now equal (namely `--sc-size-md`, while search used to be `--sc-size-md-larger`). I'm not sure if this is desired, but it does improve visual consistency and reduces code complexity.
=> Introduce sc-map element

client/elements/text/sc-text-bilara.js
Since trailing spaces have been normalize through GA, it is no longer necessary to manually add them on the front end.
=> Remove code about add trailing spaces.

client/elements/styles/sc-layout-bilara-styles.js, client/elements/styles/sc-typography-common-styles.js
This adds support for "enjambment", i.e. adding a half-line break in verse. This allows the translator to control the appearance of verse.
=> add enjambment support

client/elements/text/sc-text-bilara.js, client/utils/routingService.js
Because substr may not be supported by browsers in the future, and it happens to be used in key positions, it is replaced this time
=> Use `slice` instead of possibly deprecated `substr`

client/elements/static/sc-static-map.js, client/localization/elements/static-map_en.json
So this makes a few tweaks to the styles on the map static page.
- make columns responsive
- make map and columns as wide as the screen, no need to keep them in a text-sized container
- use pill design for feature items
- use sans-serif font for pills
- change name to "the Buddha's India"
I also in a separate commit corrected the names of the features. there were a lot of unnecessary spelling variations, and in some cases the variants were all wrong. I've eliminated all variants and ensured that those that remain are actually found in SC. I only checked the entries with variants, though, so there will probably be mistakes in the remaining items.
=> style up the maps

server/docker/Dockerfile-chrome-headless
Recently, there was a build sc-chrome-headless error when running suttacentral CI. This PR fixes this error.
=> Fix sc-chrome-headless build error
