- client/styles/sc-text-paragraph-num-styles.html
Just changed a few paragraph classes to reflect changes to numbering of Abhidhamma ID. Not sure if that needs me to go through this process of creating a new branch but just in case.
> change paragraph classes dhsk

- server/server/data_loader/arangoload.py
- server/server/data_loader/tests/test_arangoload.py
Just a small change to the comments to make it consistent with real data.
> [SUCE-248] change dhsk to dk

- client/elements/text/sc-segmented-text.html
Change the script of the Pali text doesn't work if we select script before "side by side/line by line"
> [SUCE-321] Change the script of the Pali text doesn't work if we select script before "side by side/line by line"

- client/elements/menus/settings-menu.html
"Change the script of the Pali text" has different dropdown element behaviour than others
> [SUCE-335] "Change the script of the Pali text" has different dropdown element behaviour than others 

- client/elements/text/sc-simple-text.html
- client/styles/sc-text-styles.html
Just a few small changes for textual info classes.
> [SUCE-304] adding classes & js for textual info

- client/elements/text/sc-simple-text.html
- client/styles/sc-text-styles.html
Changed title attribute to toggle on and off dependent on whether Textual Information is on or off.
Other titles are on all the time if the css shows that the specific class is visible when TI is off.
> [SUC-304] updated titles to toggle if class is visible

- client/elements/text/sc-simple-text.html
- client/package-lock.json
- client/styles/sc-text-styles.html
I have created JS & CSS for the var-classes + 2 test files for testing. The CSS needs a bit more work but the functionality is there now.
> Varcorrclass

- client/elements/text/sc-simple-text.html
Small change for pages that do not have variables in it so the color page will work.
> color page update

- client/elements/text/sc-simple-text.html
- client/styles/sc-text-styles.html
Just a few styling changes for Sujato to have a look at.
> [SUCE-272] var styling changes

- server/server/api/views.py
- server/server/common/queries.py
- server/server/common/utils.py
Updated views to properly handled Vinaya and Abhidhamma
> Suce 358 side menu

- client/elements/suttaplex/sc-suttaplex.html
- client/package-lock.json
> [SUCE-299] nerdy row test

- client/elements/menus/language-menu.html
- client/elements/page-selector.html
- client/elements/sc-donate-now-page.html
You said there was a Jira bug ticket for this but I cannot find it. So I created a new one for it. Let me know the number of the other one so I can link them.
> [SUCE-425] z-index change on toolbar when dropdown opens

- client/elements/sc-page-static.html
- client/elements/static/vinaya.html
- client/elements/text/sc-segmented-text.html
- client/elements/text/sc-simple-text.html
No SUCE for this one, just some small bug fixes Sujato asked for. You might not see any difference but the en-dashes have been replaced by em-dashes.
> small bug fixes

- client/elements/menus/sc-settings-menu.html
- client/localization/elements/sc-settings-menu/en.json
- client/localization/elements/sc-settings-menu/pl.json
Please feel free to change my Polish!
I like this localization: it's very easy and I can have localizations in each other too.
> [SUCE-288] toast notifications in 2 languages on settings menu

- server/server/common/queries.py
No ticket, just small change to query logic.
> small change to queries

- client/elements/static-templates/methodology-page.html
No SUCE ticket for this: just removing an error that prevented full methodology list to show up and adding some more.
> adding references + removing error in methodology

- server/server/data_loader/biblio.py
- server/server/data_loader/currencies.py
- server/server/data_loader/images_files.py
- server/server/data_loader/paragraphs.py
Other errors need to be fixed in nextdata.
> Eliminate "duplicate key" errors and ensure deletions are handled correctly.

- server/server/migrations/migrations/add_indexes_020.py
- server/server/migrations/migrations/add_indexes_021.py
> Added some missing indexes which marginally impaired performance

- server/server/common/queries.py
- server/server/data_loader/arangoload.py
- server/server/data_loader/order.py
- server/server/data_loader/textdata.py
- server/server/data_loader/util.py
Now correctly finds the proper next and previous text.
Checks that all texts are navigable and print errors for those which aren't.
Much faster, particularly if the collections are loaded.
> Rewrite of next/prev functionality to use menu structure.

- client/elements/suttaplex/sc-parallel-list.html
- client/elements/suttaplex/sc-suttaplex.html
Fixed:
- the translations label appearing over the dropdown label
- shaky cursor over parallels toggle
- console error when computing ids in parallels and suttaplex (the suttaplex one was passing silently)
> Various fixes

- server/server/data_loader/po.py
Also fix issue where segmented texts were not appearing in sn/an
> Fix titles of segmented texts (remove numbers)

- client/index.html
This seems to fix textual information on firefox in addition to improving performance.
> switch to webcomponents-loader.js

- client/elements/text/sc-segmented-text.html
- client/elements/text/sc-text-page.html
- client/styles/sc-text-styles.html
These are just some small fixes where the segmented texts did not work. I have not make a Jira ticket for this.
> correcting small errors segmented texts

- nginx/conf.d/sc.nginx.conf
if is evil but I'm pretty sure I use it safely here since the docs
say the only safe things you do in an if is return or rewrite
> Serve a robots.txt appropriate to the domain

- client/elements/sc-page-search.html
I've disabled one function but left the code in the file for now. I hope that if Hubert comes back he can have a look at it but for now this function causes more problems than that it is worth. At the moment I think there are more important things to look at but with this function disabled, the search results returned are correct.
> [SUCE-644] search loading

- server/server/api/views.py
> Yet another hack to the menu view to override splitting by language

- docker-compose.yml
- server/server/api/views.py
- server/server/common/queries.py
- server/server/config.py
- server/server/data_loader/arangoload.py
- server/server/data_loader/po.py
- server/server/data_loader/textdata.py
- server/server/manage.py
- server/server/search/texts.py
This is data which is not indexed and only very rarely required for a view.
> Move certain bulk data out of ArangoDB and keep it on the disk

- client/index.html
> Correctly set og:url property, and also add <link rel=canonical> as per

- client/builder.sh
> Don't be verbose (by default), can still pass --verbose to builder.sh

- client/elements/addons/text-carousel.html
- client/elements/static-templates/home-page.html
- client/elements/static/home-page.html
- client/localization/elements/static_home-page/en.json
There were some inconsistencies in the code so those might account for the problems but not sure.
I cannot recreate this problem locally so have to look on Staging.
> [SUCE-916] fixing text caroussel

- server/docker/Dockerfile-flask
repository (pointlessly) taking a very long time.
> On rebuilds other than the first, COPY . . would copy the entire data

- server/server/data_loader/dictionary_full.py
(the error was already there, just silent)
> This fixes an error which was exposed by updates to python-arango

- client/elements/styles/sc-dict-styles.js
> #948 Fix for dictionary list styling

- client/elements/static/offline-page.js
- client/index.html
- client/localization/elements/sc-offline-page/en.json
- client/localization/elements/sc-offline-page/pl.json
- docker-compose.dev.yml
> Add to home screen

- client/elements/styles/sc-text-paragraph-num-styles.html
I've added RS in the css styles to show for the numbers by Richard Solomon in the Rhinoceros Sutra in Gandhari.
Maybe somebody can be so kind as to approve this. Thanks.
> Gandhari Rhino Sutra paragraph numbers

- server/server/api/views.py
- server/server/common/queries.py
> Menu endpoint now includes yellow_brick_road parameter

- server/server/common/queries.py
> Replaced nasty hack shortcut with proper graph traversal code

- client/elements/text/sc-segmented-text.js
It is working now for textual information off but also brought up a whole lot of other issues. Some of those I have fixed in this too. I will make a ticket for the other issues but they might have to be re-writen with LIT-elements.
> SUCE-1234 highlighting when textual info is off

- client/elements/styles/sc-colors-dark.json
- server/server/data_loader/arangoload.py
No matches were found for orphans so removed some code to make the orphans come through.
> SUCE-1228 unusual parallels not loading

- client/elements/static/languages-page.js
Sort translations on "language" pages by root language
> Sort translations on "language" pages by root language

- client/elements/lookups/sc-lookup-styles.js
- client/elements/sc-page-dictionary.js
- client/elements/styles/sc-dict-styles.js
- client/elements/text/sc-segmented-text.js
- client/elements/text/sc-simple-text.js
Rewrite site components in LitElement (1): sc-lookup-styles.js
> Rewrite site components in LitElement (1): sc-lookup-styles.js

- client/elements/addons/localization-mixin.js
- client/elements/static/names-page.js
- client/elements/static/numbering-page.js
- client/elements/static/similes-page.js
- client/elements/static/subjects-page.js
- client/elements/suttaplex/card/sc-suttaplex-css.js
- client/localization/elements/static_names-page/zh.json
- client/localization/elements/static_similes-page/zh.json
- client/localization/elements/static_subjects-page/zh.json
Fixed Subjects, Similes, Names page cannot be displayed correctly For Chinese l10n
> Fixed Subjects, Similes, Names page cannot be displayed correctly For Chinese l10n

- client/elements/sc-static-page-selector.js
Corrected anti pattern "Linkify site title".
related issue #1451
> Corrected anti pattern "Linkify site title".

- client/elements/sc-drawer-layout.js
- client/elements/sc-page-selector.js
- client/redux-store.js
1. Sidebar: obey by user， when resize, if the sidebar is not opened manually, it does not open automatically.
2. The toolbar does not cover the site title.
> Sidebar: obey by user, toolbar does not cover the site title.

- client/elements/text/sc-segmented-text.js
Fixed "Root Pali text in DN does not display"(#1479)
> Fixed "Root Pali text in DN does not display"

- client/elements/suttaplex/card/sc-suttaplex.js
Add MD divider to suttaplex 
related issue: #1475
> Add MD divider to suttaplex

- client/elements/menus/sc-search-filter-menu.js
Rewrite site components in LitElement (4): sc-search-filter-menu.js 
related issue: #1436
> Rewrite site components in LitElement (4): sc-search-filter-menu.js

- client/elements/menus/sc-more-menu.js
Rewrite site components in LitElement (5): sc-more-menu.js
> Rewrite site components in LitElement (5): sc-more-menu.js

- client/elements/menus/sc-suttaplex-share-menu.js
Rewrite site components in LitElement (6): sc-suttaplex-share-menu.js
Using fetch instead of iron Ajax
> Rewrite site components in LitElement (6): sc-suttaplex-share-menu.js

- client/elements/text/sc-text-options.js
Rewrite site components in LitElement (7): sc-text-options.js
> Rewrite site components in LitElement (7): sc-text-options.js

- client/elements/sc-page-dictionary.js
1. Rewrite sc-page-dictionary.js
2. Use Fetch instead iron-ajax
> Rewrite site components in LitElement (8): sc-page-dictionary.js

- client/elements/addons/sc-nav-contents.js
- client/elements/text/sc-segmented-text.js
Fix errors that ToC does not display in Firefox
> Fix errors that ToC does not display in Firefox

- client/elements/static-templates/home-page.js
- client/elements/static/home-page.js
- client/elements/suttaplex/card/sc-parallel-list.js
- client/elements/suttaplex/sc-suttaplex-list.js
Remove references to iron-ajax.
> Remove references to iron-ajax.

- client/elements/addons/text-carousel.js
Remove references to iron-ajax: text-carousel.js
> Remove references to iron-ajax: text-carousel.js

- client/elements/lookups/sc-lzh2en.js
1. Rewrite SC component with litelement: sc-lzh2en.js.
2. Using fetch instead of iron-ajax.
> Rewrite SC component with litElement:  sc-lzh2en.js

- client/elements/lookups/sc-pli.js
1. Rewrite SC component with litElement: sc-pli.js.
2. Using fetch instead of iron-ajax.
> Rewrite SC component with litElement: sc-pli.js

- client/index.html
- client/package-lock.json
- client/package.json
- client/polymer.json
Remove ES5 bundle and polyfills and unnecessary lit-html package reference
> Remove ES5 bundle and polyfills and unnecessary lit-html package reference

- client/elements/styles/sc-text-styles.js
- client/elements/styles/static-styles.js
- client/elements/text/sc-simple-text.js
fix: Variant readings display bug in legacy texts #1342
> fix: Variant readings display bug in legacy texts #1342

- client/elements/addons/localization-mixin.js
- client/elements/menus/sc-settings-menu.js
1. Rewrite sc-settings-menu component with litElement.
2. Used fetch instead of iron-ajax
> Rewrite sc-settings-menu component with litElement.

- client/elements/sc-page-selector.js
- client/elements/sc-static-page-selector.js
1. Attach the Adaptive Tab Bar to the standard toolbar
2. Rewrite sc-static-page-selector.js with litelement
3. Reduce horizontal padding for toolbar elements on small screens **when window resize**
4. Improve for : Heal the sliced toolbar #1448
> Attach the Adaptive Tab Bar to the standard toolbar

- client/elements/sc-page-selector.js
- client/elements/sc-static-page-selector.js
> Improve toolbar behavior.

- client/elements/sc-static-page-selector.js
In mobile browser, do not attach ATB to main toolbar.
> In mobile browser, do not attach ATB to main toolbar.

- client/elements/sc-static-page-selector.js
cancel: Attach the Adaptive Tab Bar to the standard toolbar
> cancel: Attach the Adaptive Tab Bar to the standard toolbar

- client/elements/menus/sc-toolbar.js
- client/redux-store.js
Solve search field  responsive behaviour abnormal in firefox.
> Solve search field  responsive behaviour abnormal in firefox.

- client/elements/text/sc-text-page-selector.js
Because it is not possible to load bilara data by reading a json file, you need to develop a new API and then re-enable the new text page.
> Turn off the new text page.

- client/elements/text/sc-bilara-segmented-text.js
- client/elements/text/sc-text-page.js
Modify the parent class of the sc-bilara-segmented-text.js component
> Modify the parent class of the sc-bilara-segmented-text.js component

- client/elements/sc-page-search.js
Fixed inconsistency between search page and previous version style.
> Fixed inconsistency between search page and previous version style.

- client/elements/text/sc-text-page-selector.js
Fix: 'you're offline' flashing before showing text page.
> Fix: 'you're offline' flashing before showing text page.

- client/package-lock.json
- client/package.json
Update lit-element to the latest version.
> Update lit-element to the latest version.

- client/elements/sc-page-search.js
Delete unnecessary `updated` event.
> Optimize search page.

- server/server/migrations/migrations/initial_migration_001.py
Create 'segmented_data' collection to arangodb when run 'make migrate'.
> Create 'segmented_data' collection to arangodb when run 'make migrate'

- client/elements/addons/sc-toasts.js
- client/package.json
- nginx/conf.d/prod.nginx.conf
1. Rewrite sc-toast.js with litelement.
2. Use mwc-snackbar instead of paper-toast.
3. update prod.nginx.conf(Content-Security-Policy)
4. update package.json, delete reference of 'dile-toast'.
> Rewrite sc-toast.js with litelement.

- client/elements/styles/sc-bilara-segmented-text-styles.js
- client/elements/text/sc-bilara-segmented-text.js
I have removed the minimap, it has too many bugs and we need to focus on more important features. See here:
https://github.com/suttacentral/suttacentral/issues/1149#issuecomment-621509375
> remove minimap

- client/package.json
> Add paper-tooltip reference.

- client/elements/static/donate-now-page.js
- client/elements/text/sc-segmented-text.js
- client/package.json
Remove paper-toast and paper-tooltip reference.
> Remove paper-toast and paper-tooltip reference.

- client/index.html
Add Material Icons font reference.
> Add Material Icons font reference.

- client/elements/text/sc-text-options.js
Delete the paper-tooltip of sc-text-options.
> Delete the paper-tooltip of sc-text-options.

- client/elements/addons/sc-bottom-sheet.js
Format the code for sc-bottom-sheet.js
> Format the code for sc-bottom-sheet.js.

- client/elements/styles/sc-text-heading-styles-new.js
- client/elements/styles/sc-text-styles-new.js
- client/elements/text/sc-simple-text.js
Override the style of sc-simple-text.js
> Override the style of sc-simple-text.

- client/elements/addons/sc-bottom-sheet.js
- client/elements/addons/sc-top-sheet.js
- client/elements/styles/sc-bilara-segmented-text-styles.js
- client/elements/text/sc-bilara-segmented-text.js
- client/localization/elements/sc-top-sheet/zh.json
- client/redux-store.js
Adjust sc-top-sheet according to test feedback.
> Adjust sc-top-sheet according to test feedback.

- client/elements/addons/sc-top-sheet.js
> Fix: rememberSetting failure.

- client/elements/addons/sc-top-sheet.js
- client/elements/text/sc-bilara-segmented-text.js
- client/localization/elements/sc-top-sheet/en.json
- client/localization/elements/sc-top-sheet/zh.json
- client/redux-store.js
Add `show highlighting` option for sc-top-sheet.
> Add `show highlighting` option for sc-top-sheet.

- client/elements/text/sc-simple-text.js
Add `highlight` and 'legacy-reference' class name to the article tag of sc-simple-text.js.
> Add `highlight` and 'legacy-reference' class name to sc-simple-text.js.

- client/elements/styles/sc-typography-static-styles.js
> Remove extra brackets.

- client/elements/static/home-page.js
Format the code of home-page.js
> Format the code of home-page.js

- client/elements/text/sc-bilara-segmented-text.js
Fix bug when loading `vaggasuttas`.
> Fix bug when loading `vaggasuttas`. 

- client/elements/sc-page-selector.js
- client/elements/static/home-page.js
- client/elements/styles/sc-typography-bilara-styles.js
- client/elements/styles/sc-typography-common-styles.js
- client/elements/styles/sc-typography-legacy-styles.js
- client/elements/styles/sc-typography-static-styles.js
This a quick merge to test out a proposed tweak to the Home page button
> Sujato work

- client/elements/static/home-page.js
> formatting home-page.js code.

- client/elements/text/sc-bilara-segmented-text.js
- client/localization/elements/sc-text/en.json
- client/localization/elements/sc-text/zh.json
> Code tweak and localization.

- client/elements/styles/sc-layout-simple-styles.js
Fix the error that the vaggasuttas display is not centred.
> fix simple-text error when displaying vaggasuttas.

- client/elements/text/sc-simple-text.js
Since vaggasuttas has multiple <article> tags, so need to modify the corresponding code.
> Fix a bug about display vaggasuttas.

- client/elements/menus/sc-more-menu.js
- client/elements/menus/sc-toolbar.js
- client/elements/navigation/sc-linden-leaves.js
- client/elements/navigation/sc-navigation-common.js
- client/elements/navigation/sc-navigation-styles.js
- client/elements/navigation/sc-navigation.js
- client/elements/navigation/sc-tipitaka.js
- client/elements/sc-drawer-layout.js
- client/elements/sc-page-search.js
- client/elements/sc-page-selector.js
- client/elements/sc-static-page-selector.js
- client/elements/static/home-page.js
- client/elements/styles/sc-dict-styles.js
- client/elements/styles/sc-page-selector-styles.js
- client/elements/styles/sc-static-page-selector-styles.js
- client/elements/suttaplex/card/sc-suttaplex-css.js
- client/elements/text/sc-bilara-segmented-text.js
- client/elements/text/sc-simple-text.js
- client/elements/text/sc-text-page-selector.js
- client/index.html
- client/localization/elements/sc-linden-leaves/en.json
- client/localization/elements/sc-navigation/en.json
- client/package.json
- client/redux-store.js
> New navigation system.

- client/elements/menus/sc-toolbar.js
- client/elements/navigation/sc-navigation.js
Code adjustment of navigation system.
> Code adjustment of navigation system.

- client/elements/navigation/sc-navigation-styles.js
- client/elements/navigation/sc-navigation.js
- client/elements/navigation/sc-tipitaka.js
Add bouncing loader to navigation component.
> Add bouncing loader to navigation component.

- client/elements/addons/sc-top-sheet.js
- client/elements/menus/sc-toolbar.js
- client/elements/navigation/sc-linden-leaves.js
- client/elements/navigation/sc-navigation-styles.js
- client/elements/navigation/sc-navigation.js
- client/elements/navigation/sc-tipitaka.js
- client/elements/sc-drawer-layout.js
- client/elements/static/home-page.js
- client/elements/styles/sc-colors-light.json
- client/elements/styles/sc-layout-bilara-styles.js
- client/elements/styles/sc-typography-common-styles.js
- client/elements/suttaplex/card/sc-suttaplex-css.js
- client/elements/suttaplex/card/sc-suttaplex.js
- client/localization/elements/static_abhidhamma-page/en.json
- client/localization/elements/static_discourses-page/en.json
- client/localization/elements/static_vinaya-page/en.json
This PR includes a range of changes to styles and other details, mostly for the navigation.
> Sujato styles

- client/elements/addons/localization-mixin.js
Optimize the logic of localized function.
> Optimize the logic of localized function.

- client/elements/navigation/sc-navigation-common.js
- client/elements/navigation/sc-navigation.js
- client/elements/sc-page-search.js
Modify the navigation level according to the feedback of issue #1664.
> Fix wrong navigation level.

- client/package.json
Downgrade webpack-related js packages.
> Downgrade webpack related js packages.

- client/elements/menus/sc-more-menu.js
Add a ripple effect to the more-menu.
> Add a ripple effect to the more-menu.

- client/localization/elements/sc-site-layout/en.json
- client/localization/elements/sc-site-layout/pl.json
- client/localization/elements/sc-site-layout/pt.json
- client/localization/elements/sc-site-layout/zh.json
Use ordinary Capital Case for the text in the tab bar.
> Use ordinary Capital Case for the text in the tab bar.

- client/elements/menus/sc-action-items.js
- client/elements/sc-site-layout.js
- client/elements/styles/sc-site-layout-styles.js
Adjust the position of the search input box and SC title in different width interface.
> Adjust the position of the search input box and SC title.

- client/elements/styles/sc-site-layout-styles.js
- client/elements/styles/sc-static-page-selector-styles.js
Some style adjustments. I forgot to make a PR for this a few days ago!
> adjust some header styles

- client/elements/styles/sc-site-layout-styles.js
- client/elements/text/sc-text-page-selector.js
This makes two changes. 
One is simple: add a space in the title for texts so there is a space on either side of the dash.
The second is more subtle. There was `will-change: transform` applied to `.transitionTransform`. This is a hint to the browser that the element will be transformed, and gives the browser time to optimize. 
However, this property is harmful if overused, as it prematurely optimizes and can end up wasting browser resources. As such, it is recommended that it is only used when necessary, and usually it is added and removed by JS. See [this article](https://dev.opera.com/articles/css-will-change-property/) for details.
For this reason, in my original demo, I added and removed this class via JS, see the note in `sc-page-selector-styles.js`. However now the class is …
> Sujato work1

- client/elements/menus/sc-action-items.js
- client/elements/menus/sc-more-menu.js
- client/elements/menus/sc-universal-action-items.js
- client/elements/navigation/sc-linden-leaves.js
- client/elements/navigation/sc-navigation-styles.js
- client/elements/sc-page-selector.js
- client/elements/sc-site-layout.js
- client/elements/styles/sc-site-layout-styles.js
- client/localization/elements/sc-universal-action-items/en.json
- client/localization/elements/sc-universal-action-items/pl.json
- client/localization/elements/sc-universal-action-items/pt.json
- client/localization/elements/sc-universal-action-items/zh.json
- client/redux-store.js
This makes some very small changes to the Home page, mainly the header.
- Use `<h1>` tag on Home page title to make it more semantic.
- Remove `<a>` tags from Home page title and subtitle. These are not links.
- Separate the layout and text styling CSS for the main heading.
- Adjust styles, remove unneeded CSS.
- Use proper `var()` for font-family.
In addition, I use flex properly to size contents of nav cards on Home page. Here you can see the problem that this solves.
> Sujato header

- client/elements/menus/sc-action-items.js
- client/elements/menus/sc-more-menu.js
- client/elements/menus/sc-universal-action-items.js
- client/elements/navigation/sc-linden-leaves.js
- client/elements/sc-page-selector.js
- client/elements/sc-site-layout.js
- client/elements/styles/sc-site-layout-styles.js
- client/localization/elements/sc-universal-action-items/en.json
- client/localization/elements/sc-universal-action-items/pl.json
- client/localization/elements/sc-universal-action-items/pt.json
- client/localization/elements/sc-universal-action-items/zh.json
- client/redux-store.js
Migrate search and more buttons to the breadcrumb toolbar
> Migrate search and more buttons to the breadcrumb toolbar.

- client/elements/navigation/sc-navigation-styles.js
- client/elements/sc-page-search.js
- client/elements/sc-page-selector.js
- client/elements/static/home-page.js
- client/elements/styles/sc-utility-styles.js
These changes were required because there was no horizontal margin on the text pages. I have added these via `.container`, and have incidentally adjusted a few styles.
Also not I have changed the text for the Home page "Discourses" card.
> Sujato margin

- client/elements/menus/sc-more-menu.js
- client/elements/menus/sc-universal-action-items.js
- client/elements/navigation/sc-linden-leaves.js
1. Clean up unwanted scroll bar on more-menu.
2. Remove unnecessary html tag and css.
> Clean up unwanted scroll bar on more-menu.

- client/elements/sc-site-layout.js
- client/redux-store.js
When the text setting is set to not save, the breadcrumb navigation item will be reset to the default value after page redirect.
> Fixed a problem with breadcrumb navigation item reset in some cases.

- client/elements/navigation/sc-linden-leaves.js
- client/elements/sc-page-dictionary.js
1. Fixed a bug that covered the universal action items because the breadcrumb items were too long.
2. Code formatting and clearing unnecessary code.
> Fixed a bug that covered the universal action items.

- client/elements/addons/sc-toasts.js
- client/elements/addons/sc-top-sheet.js
- client/localization/elements/sc-top-sheet/en.json
- client/localization/elements/sc-top-sheet/zh.json
Add setting tips for text setting.
> Add setting tips for text setting.

- client/elements/navigation/sc-linden-leaves.js
- client/elements/text/sc-text-page-selector.js
> make breadcrumbs 48px height

- client/elements/sc-page-selector.js
Solve the problem of webpack loading error.
> Solve the problem of webpack loading error.

- client/elements/navigation/sc-navigation.js
- client/elements/text/sc-text-page-selector.js
1. Breadcrumbs use acronym (acro) where possible.
> Breadcrumbs use acronym (acro) where possible.

- client/elements/navigation/sc-navigation-styles.js
- client/elements/navigation/sc-navigation.js
- client/redux-store.js
Since getting the blurb related api returns a lot of data, the first display of the blurb will be slower, but I cached the blurb data to the localstorage, so the second display will be faster.
>  Add blurbs to nav cards.

- client/elements/static-templates/home-page.js
- client/index.html
- nginx/conf.d/prod.nginx.conf
> Remove Vimeo related code.

- docker-compose.yml
Upgrade ArangoDB version to 3.7.3
> Upgrade ArangoDB version to 3.7.3

- client/elements/menus/sc-action-items.js
> Fixed a button display error.

- client/elements/addons/localization-mixin.js
- client/elements/sc-site-layout.js
Let App bar disappear and reappear on scroll.
> Let universal toolbar disappear and reappear on scroll.

- client/elements/menus/sc-action-items.js
- client/elements/menus/sc-more-menu.js
- client/elements/sc-site-layout.js
- client/elements/text/sc-bilara-segmented-text.js
- client/localization/elements/sc-more-menu/en.json
- client/localization/elements/sc-more-menu/zh.json
- client/redux-store.js
1. Migrate theme button to more menu.
2. Add always show toolbar option to more menu.
3. Adjust the response frequency of toolbar scrolling events.
4. Add a visual indicator when the top sheet and the suttaplexs card is visible.
> Migrate theme button and add always show toolbar option to more menu.

- client/elements/navigation/sc-navigation-styles.js
- client/elements/navigation/sc-navigation.js
- client/elements/navigation/sc-tipitaka.js
1.Remove block link.
2.Remove morph-ripple and paper-ripple.
3.Use normal links on cards.
4.Wrap the entire `<header>` element in a link.
5.Blurb has to click to expand and shrink.
6.Add prefix number in card title.
> Nav cards: Remove block link, add blurb read more function.

- nginx/conf.d/prod.nginx.conf
Adjust Content-Security-Policy.
> Adjust Content-Security-Policy.

- client/elements/navigation/readMoreJS.min.js
- client/elements/styles/sc-site-layout-styles.js
> Let more-menu always on top.

- client/elements/menus/sc-action-items.js
- client/elements/sc-site-layout.js
- client/elements/styles/sc-site-layout-styles.js
- client/elements/text/sc-text-page-selector.js
Give context toolbar responsive height on text pages.
> Give context toolbar responsive height on text pages.

- client/elements/menus/sc-action-items.js
- client/elements/menus/sc-universal-action-items.js
- client/elements/styles/sc-site-layout-styles.js
- client/elements/suttaplex/card/sc-sutta-parallels.js
1.Hide top sheets when more menu open.
2.Fix a merge conflict.
> Hide top sheets when more menu open.

- client/elements/menus/sc-action-items.js
Fix:The icons border color does not match when switching colors.
> Fix:The icons border color does not match.

- client/elements/styles/sc-typography-bilara-styles.js
I've removed the styling but to be honest I do not know how to remove the broken reference from the content. Therefore the content changes doesn't include in the PR. 
#1650
> #1650 | remove css

- server/server/data_loader/arangoload.py
- server/server/migrations/migrations/add_super_nav_detail_collections_026.py
migrations with needed collections created
> Add migrations

- client/elements/text/sc-text-page-selector.js
Fixes errors where breadcrumbs navigation data are incorrect in some cases.
> Fix breadcrumb navigation data errors.

- server/server/data_loader/arangoload.py
- server/server/migrations/migrations/add_child_range_collection_027.py
child ranges from from the sc-data/structure/child_range.json file will be loaded to the child_range collection in the ArangoDB
> #1826 Load child_range into the database

- client/package.json
Add the @babel/preset-env package that need for optimize-plugin.
> Add the @babel/preset-env package.

- client/elements/navigation/sc-linden-leaves.js
- client/elements/navigation/sc-navigation.js
- client/elements/navigation/sc-tipitaka.js
- client/elements/text/sc-text-page-selector.js
- client/redux-store.js
According to the new data structural adjustment navigation module.
> Adjustment navigation module.

- client/elements/addons/text-carousel.js
- client/elements/menus/sc-more-menu.js
- client/elements/sc-site-layout.js
- fix ripple
- fix vertical alignment
> remove morph ripple, fix vertical alignment of items

- server/server/common/queries.py
translated name support added using new collection `names`
> 1781 | Add translated name support

- server/server/api/views.py
- server/server/common/queries.py
- server/server/data_loader/arangoload.py
- server/server/migrations/migrations/add_yellow_brick_road_changes_030.py
- #1859 done
- created new yellow_brick_road collection
- v_text view updated
- migration added
- added table population during load-data script
- population queries added to the queries.py
- navigation API changed in the views.py
> #1859 | Add new yellow_brick_road

- client/elements/addons/sc-top-sheet-toc.js
- client/elements/menus/sc-action-items.js
- client/elements/navigation/sc-tipitaka.js
- client/elements/styles/sc-typography-legacy-styles.js
- client/elements/text/sc-simple-text.js
- client/localization/elements/sc-top-sheet/en.json
this fixes two out of three of the outstanding ToC issues
> fixes to toc

- server/server/api/views/__init__.py
- server/server/api/views/glossary.py
- server/server/api/views/views.py
- server/server/common/queries.py
- server/server/data_loader/arangoload.py
- server/server/data_loader/dictionaries.py
- server/server/migrations/migrations/add_glossaries_032.py
- #1886 glossary loading added
- add all glossaries to the /glossary api
- created glossary migration
- load-data glossary loading
> # 1886 | Add glossaries

- client/elements/navigation/sc-navigation.js
- client/elements/navigation/sc-tipitaka.js
Fixed: When you change the site language, it changes the language name in the YBR, but it doesn't update the number of translations.
> Fix a bug in the YBR.

- client/elements/menus/sc-more-menu.js
- client/elements/navigation/sc-navigation-styles.js
- client/elements/navigation/sc-navigation.js
- client/elements/navigation/sc-tipitaka.js
- client/elements/suttaplex/card/sc-suttaplex-css.js
- client/elements/suttaplex/card/sc-suttaplex.js
This makes a number of small adjustments to various things.
- adjust spacing of switch in more-menu
- use better names for share menu in suttaplex
- fix style and display of details in suttaplex nerdy-row
- adjust style of YBR, make less prominent and remove check
- add child range to high level collections
> Sujato nerdy tweaks

- server/server/common/queries.py
- server/server/data_loader/arangoload.py
- added AQL query to add children root_lang
> Set root_lang for all children with root_lang parent

- client/elements/menus/sc-universal-action-items.js
- client/elements/navigation/sc-linden-leaves.js
I made a search box based on the ideas here:
https://github.com/suttacentral/suttacentral/issues/1930
To my surprise I was actually able to get it working pretty well!
> make cool search box with mwc

- client/elements/addons/sc-bottom-sheet.js
- client/elements/lookups/sc-pli.js
- client/elements/menus/sc-search-filter-menu.js
- client/elements/navigation/sc-navigation-styles.js
- client/elements/navigation/sc-navigation.js
- client/elements/sc-page-search.js
- client/elements/static/donate-now-page.js
- client/elements/styles/sc-typography-bilara-styles.js
- client/elements/text/sc-stepper.js
This one mainly styles the Pali lookup in the bottom sheet.
> Sujato lookup

- server/server/data_loader/arangoload.py
- server/server/migrations/migrations/add_guides_and_pali_reference_edition_collections_034.py
- migration with collections added
- guides.json file parsing
- pali_reference_edition.json file parsing
#1942
> #1942 | Added guides and pali_reference_edition

- server/requirements.txt
- server/server/api/views/views.py
- server/server/common/queries.py
- server/server/migrations/migrations/add_indexes_bilara_texts_and_names_035.py
- add names index for uid, lang and uid+lang fields
- add sc_bilara_texts index for uid and uid+muids[*]
#1947
> #1947 | Add indexes for names and sc_bilara_texts

- server/server/api/views/publication.py
- server/server/app.py
- server/server/config.py
- changed swagger version
- added publication API doc
#1982
> #1982 | Swagger fix

- client/elements/text/sc-text-page-selector.js
- server/server/api/views/views.py
- server/server/common/queries.py
- server/server/data_loader/sc_bilara_data.py
`keys_order` field added to the response body
#1992
> #1992 | Use array for segment data

- client/elements/navigation/sc-navigation-common.js
- client/elements/suttaplex/sc-suttaplex-list.js
- client/elements/text/sc-text-page-selector.js
In some cases, the breadcrumbs are not updated
e.g.
http://localhost/an7.1
http://localhost/dn7
http://localhost/sn55.1
...
> Fixed: In some cases, the breadcrumbs are not updated

- client/elements/menus/sc-universal-action-items.js
- client/elements/navigation/sc-linden-leaves.js
- client/elements/sc-page-selector.js
- client/elements/sc-site-layout.js
Loay load `sc-action-items` will make main.js About 50K reduction.
> Lazy-load sc-action-items.

- client/elements/addons/sc-top-sheet-publication-bilara.js
- server/server/common/queries.py
e.g.  http://localhost/thag1.1/en/sujato
> Display collaborators info in publication details.

- client/elements/text/sc-simple-text.js
- client/elements/text/sc-stepper.js
- client/elements/text/sc-text-page-selector.js
- server/server/common/queries.py
Problem description:
[https://discourse.suttacentral.net/t/suttacentral-2021-bug-reports-here/19609/98?u=hongda](https://discourse.suttacentral.net/t/suttacentral-2021-bug-reports-here/19609/98?u=hongda)
e.g.
[http://localhost/sa87/en/analayo](http://localhost/sa87/en/analayo)
Click the `Next` Button, an error will occur.
> Fix: Click previous/next,If there is no relevant translation, an error will occur.

- client/elements/menus/sc-action-items.js
- client/elements/sc-page-selector.js
- client/elements/suttaplex/card/sc-parallel-list.js
- client/elements/text/sc-bilara-segmented-text.js
- client/elements/text/sc-text-page-selector.js
- server/server/common/queries.py
e.g.
[http://localhost/thig5.12/de/sabbamitta](http://localhost/thig5.12/de/sabbamitta)
> Fix: Segmented text: Click previous/next,If there is no relevant translation, an error will occur. 

- client/elements/suttaplex/card/sc-suttaplex.js
- client/utils/suttaplex.js
- server/server/common/queries.py
- server/server/data_loader/arangoload.py
- server/server/migrations/migrations/add_text_extra_info_038.py
1. Add `text_extra_info.json` to `ArangoDB`
2. Modified API: `/api/suttaplex`
> Add alt_volpage data to nerdy row where present.

- client/elements/navigation/sc-navigation-common.js
- client/elements/navigation/sc-navigation-tipitaka.js
- client/elements/navigation/sc-navigation.js
This PR is optimized for `Keep navigation data in sc-data/structure`
> Optimize code with new JS features.

- client/elements/addons/sc-aksharamukha-converter.js
- client/elements/addons/sc-top-sheet-views.js
Only retain the English names in the pali script dropdown.
> Fix: Transliteration: Many of the script labels are gibberish(2)

- server/server/common/queries.py
- server/server/data_loader/arangoload.py
- server/server/migrations/migrations/add_shortcuts_040.py
Need to execute `make load-data`
> Fix: Sometimes translated titles are not being used.

- server/server/data_loader/arangoload.py
Fixed duplicate titles in some cases.
Need to execute: `make delete-database`, `make load-data`
> Fix: Sometimes translated titles are not being used.(2)

- client/elements/styles/sc-layout-bilara-styles.js
- client/elements/styles/sc-typography-bilara-styles.js
- client/elements/styles/sc-typography-common-styles.js
- CSS for verses without `<br>` tags
- also some fixes for styles in bilara texts
> Sujato verse html

- client/elements/navigation/sc-navigation-tipitaka.js
- server/server/api/views/__init__.py
- server/server/api/views/views.py
- server/server/app.py
- server/server/common/queries.py
A newly introduced API, `/api/tipitaka_menu`, reduces unnecessary data transmission.
Delete unnecessary code, reduce references, and speed up loading.
> Fix High LCP in mobile.

- client/elements/static/sc-static-offline.js
- client/localization/elements/sc-offline-page/en.json
- client/localization/elements/sc-offline-page/zh.json
- nginx/conf.d/sc.nginx.conf
- server/server/api/views/views.py
- server/server/common/queries.py
1. Increase the nginx buffer size, increase the timeout period to prevent 504 time-out error.
2. Reduce unnecessary data requests.
> Fix:PWA download fails #2197

- client/elements/addons/sc-top-sheet-parallels.js
- client/elements/addons/sc-top-sheet-publication-bilara.js
- client/elements/menus/sc-action-items.js
- client/elements/sc-page-search.js
- client/elements/sc-page-selector.js
- client/elements/suttaplex/card/sc-suttaplex.js
- client/elements/suttaplex/sc-suttaplex-list.js
- client/elements/text/sc-text-page-selector.js
Optimize the dynamic loading of modules to increase speed and reduce network requests and avoid loading failure 
The relevant modules are:
1. sc-suttaplex.js
2. sc-action-items.js
3. sc-top-sheet-views.js
4. sc-top-sheet-toc.js
5. sc-top-sheet-parallels.js
6. sc-top-sheet-publication-legacy.js
7. sc-top-sheet-publication-bilara.js
Verification: All modules should be loaded normally as before。
> Optimize module dynamic loading code.

- docker-compose.yml
Update guide:
[ArangoDB Update guide](https://github.com/suttacentral/suttacentral/wiki/Upgrading-ArangoDB-docker-container)
> Upgrade the version of `ArangoDB`  to 3.8.0

- client/elements/navigation/sc-navigation-common.js
1.Speed up the breadcrumb loading.
2.Reduce the chance of errors.
> Rewrite the breadcrumb related code.

- nginx/conf.d/dev.nginx.conf
- nginx/conf.d/prod.nginx.conf
- nginx/conf.d/sc.nginx.conf
- server/server/app.py
Tuned the cache settings, adding cache lock and an explicit key
For testing added a dev setting which deletes cache entries after 1 minute
> I realized the wrong module was used, uwsgi_pass should use uwsgi_cache not proxy_cache.

- client/elements/addons/sc-redux-actions.js
- client/elements/text/sc-text-bilara.js
e.g.
http://localhost/sn1.6/en/sujato?layout=column
http://localhost/sn1.6/en/sujato?layout=row
http://localhost/sn1.6/en/sujato?script=Ahom
http://localhost/sn1.6/en/sujato?notes=tooltip
http://localhost/sn1.6/en/sujato?notes=sidenote
http://localhost/dn1/en/sujato?reference=pts/main
http://localhost/sn1.6/en/sujato?layout=row&notes=tooltip&script=Cham&reference=pts/main
> Let users share state of text by extending URLs.

- client/elements/styles/sc-layout-bilara-styles.js
- client/elements/text/sc-text-bilara.js
Related Issues:
https://github.com/suttacentral/suttacentral/issues/2147
https://github.com/suttacentral/suttacentral/issues/2148
> Fix:Hash # in URLs does not work as expected.

- client/elements/text/sc-text-bilara.js
Description: discourse.suttacentral.net/t/suttacentral-2021-bug-reports-here/19609/125?u=hongda
> Fix: Back button has problems in some cases.

- client/elements/sc-page-selector.js
- client/elements/sc-site-layout.js
Related issues:
https://github.com/suttacentral/suttacentral/issues/2313
https://github.com/suttacentral/suttacentral/issues/2314
> FIx: ATB and title for static page essays is buggy

- client/elements/menus/sc-menu-static-pages-nav.js
- client/elements/sc-page-selector.js
- client/elements/static/sc-static-pali-tipitaka.js
http://localhost/pali-tipitaka
> Add page Pali Tipitaka.

- client/elements/suttaplex/card/sc-suttaplex.js
Related issue: https://github.com/suttacentral/suttacentral/issues/2265
> Reduce or remove need for plurals.

- client/elements/publication/sc-publication-edition-matter.js
- client/elements/sc-page-selector.js
- server/server/data_loader/arangoload.py
> >According to the latest rules, pli-tv-bi-vb in super_extra_info.json is acronym as Bi, so the new acronym for pli-tv-bi-vb-pd2-8 after conversion is equal to Bi –pd2–8
> 
> No, the new version should be Bi Pd 2–8. I'll update the original issue.
Need to execute:
`make delete-database`
`make load-data`
> Format acronym by rules.

- client/elements/sc-page-search.js
- client/elements/styles/sc-dict-styles.js
- client/elements/styles/sc-static-home-styles.js
- client/elements/styles/sc-typography-bilara-styles.js
- client/elements/styles/sc-typography-common-styles.js
Addresses this:
https://github.com/suttacentral/bilara-data/issues/1911
> Sujato list numbers

- docker-compose.yml
Need to run the following to have it upgrade the database:
```
docker-compose stop sc-arangodb
docker-compose run sc-arangodb arangod --database.auto-upgrade
docker-compose start sc-arangodb
```
> Upgrade ArangoDB version to 3.9.3
